# Generated by Django 3.2 on 2022-12-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cetegory',
            new_name='category',
        ),
    ]
